export const products = [{
    name: "Pasta",
    image: "https://gdg-react-workshop.s3.amazonaws.com/pasta.JPG"
}, {
    name: "Bread",
    image: "https://gdg-react-workshop.s3.amazonaws.com/bread.JPG"
}, {
    name: "Breakfast cereal",
    image: "https://gdg-react-workshop.s3.amazonaws.com/cereal.JPG"
}, {
    name: "Butter",
    image: "https://gdg-react-workshop.s3.amazonaws.com/butter.JPG"
}, {
    name: "Milk",
    image: "https://gdg-react-workshop.s3.amazonaws.com/milk.JPG"
}, {
    name: "Eggs",
    image: "https://gdg-react-workshop.s3.amazonaws.com/eggs.JPG"
}, {
    name: "Cheese",
    image: "https://gdg-react-workshop.s3.amazonaws.com/cheese.JPG"
}, {
    name: "Onions",
    image: "https://gdg-react-workshop.s3.amazonaws.com/onions.JPG"
}, {
    name: "Banana",
    image: "https://gdg-react-workshop.s3.amazonaws.com/banana.JPG"
}, {
    name: "Apples",
    image: "https://gdg-react-workshop.s3.amazonaws.com/apples.JPG"
}, {
    name: "Kiwi",
    image: "https://gdg-react-workshop.s3.amazonaws.com/kiwi.JPG"
}, {
    name: "Tomatoes",
    image: "https://gdg-react-workshop.s3.amazonaws.com/tomato.JPG"
}, {
    name: "Avocado",
    image: "https://gdg-react-workshop.s3.amazonaws.com/avacado.JPG"
}, {
    name: "Honey",
    image: "https://gdg-react-workshop.s3.amazonaws.com/honey.JPG"
}, {
    name: "Watermelon",
    image: "https://gdg-react-workshop.s3.amazonaws.com/watermelon.JPG"
}, {
    name: "Chicken",
    image: "https://gdg-react-workshop.s3.amazonaws.com/chicken.JPG"
}];